/* vim: set sts=4 sw=4 et: */

/* Titan Icon
 * Copyright (C) 2013 Titan Network
 * All Rights Reserved
 *
 * This code is for educational purposes only and is not licensed for
 * redistribution in source form.
 */

enum {
    COHVAR_BINDS = 1,
    COHVAR_CAMERA,
    COHVAR_CAM_IS_DETACHED,
    COHVAR_CLASS_TBL,
    COHVAR_CONTROLS,
    COHVAR_CONTROLS_FROM_SERVER,
    COHVAR_DEFAULT_BINDS,
    COHVAR_EDIT_TRANSFORM_ABS,
    COHVAR_ENT_CHAR_OFFSET,
    COHVAR_ENT_DEMO_OFFSET,
    COHVAR_ENT_FLAGS_OFFSET,
    COHVAR_ENT_NEXT_MOV_OFFSET,
    COHVAR_ENT_SERVERID_OFFSET,
    COHVAR_ENT_TYPES,
    COHVAR_ENTTBL,
    COHVAR_GAME_TIME,
    COHVAR_GAME_TIME_STEP,
    COHVAR_MAP_ROOT,
    COHVAR_NPC_LIST,
    COHVAR_NOCOLL,
    COHVAR_PLAYER_ENT,
    COHVAR_PLAYER_KBOFFSET,
    COHVAR_ORIGIN_TBL,
    COHVAR_SEEALL,
    COHVAR_SCHEMA_COSTUME,
    COHVAR_START_CHOICE,
    COHVAR_TARGET,
    COHFUNC_ANNOYING_ALERT,
    COHFUNC_ARRAY_LOOKUP,
    COHFUNC_BACKSLASH_FIX,
    COHFUNC_BIN_CLEAR,
    COHFUNC_BIN_INIT,
    COHFUNC_BIN_LOADFILE,
    COHFUNC_BIND_PUSH,
    COHFUNC_BIND,
    COHFUNC_CALLOC,
    COHFUNC_CHKSTK,
    COHFUNC_CMD_INIT,
    COHFUNC_CMD_PARSE,
    COHFUNC_CLEAR_ENTS,
    COHFUNC_COSTUME_DIR,
    COHFUNC_COPY_ATTRIBS,
    COHFUNC_DETACH_CAMERA,
    COHFUNC_DIALOG,
    COHFUNC_DIALOG_GET_TEXT,
    COHFUNC_ENT_COSTUME_UPDATED,
    COHFUNC_ENT_FREE,
    COHFUNC_ENT_INITCHAR,
    COHFUNC_ENT_INITPLAYER,
    COHFUNC_ENT_MOVE,
    COHFUNC_ENT_NEW,
    COHFUNC_ENT_PREPARE_COSTUME,
    COHFUNC_ENT_SET_COSTUME,
    COHFUNC_ENT_SET_COSTUME_NPC_PTR,
    COHFUNC_ENT_SET_MATRIX,
    COHFUNC_ENT_TELEPORT,
    COHFUNC_FREE_ARRAY,
    COHFUNC_GET_CLASS,
    COHFUNC_GET_NPC_COSTUME_IDX,
    COHFUNC_GET_NPC_COSTUME_PTR,
    COHFUNC_GET_ORIGIN,
    COHFUNC_HASH_CLEAR,
    COHFUNC_HASH_CREATE,
    COHFUNC_HASH_FREE,
    COHFUNC_HASH_INSERT,
    COHFUNC_HASH_LOOKUP,
    COHFUNC_INIT_KEYBINDS,
    COHFUNC_LOAD_MAP_DEMO,
    COHFUNC_MAP_CLEAR,
    COHFUNC_MATRIX_FROM_PYR,
    COHFUNC_MATRIX_TO_PYR,
    COHFUNC_MOV_BY_NAME,
    COHFUNC_RAND,
    COHFUNC_STRCAT_S,
    COHFUNC_STRCPY,
    COHFUNC_TRANSLATE,
    COHFUNC_WALK_MAP,
    COH_END
};

void InitCoh(int vers);
unsigned long CohAddr(int id);

void PatchI24();
void PatchI23();
