/* vim: set sts=4 sw=4 et: */

/* Titan Icon
 * Copyright (C) 2013 Titan Network
 * All Rights Reserved
 *
 * This code is for educational purposes only and is not licensed for
 * redistribution in source form.
 */

enum {
    STR_ICON_VERSION = 1,
    STR_NOCLIP_ON,
    STR_NOCLIP_OFF,
    STR_MAPFILE,
    STR_MOV,
    STR_FX,
    STR_CAMERADETACH,
    STR_CAMERAATTACH,
    STR_HOLDTORCH,
    STR_MAP_OUTBREAK,
    STR_MAP_ATLAS,
    STR_MAP_NERVA,
    STR_MAP_POCKETD,
    STR_MAP_NOVA,
    STR_MAP_IMPERIAL,
    STR_DEFAULT_CLASS,
    STR_DEFAULT_ORIGIN,
    STR_SPAWNLOCATION,
    STR_PERSISTENTNPC,
    STR_DOOR,
    STR_GENERATOR,
    STR_DUMMY_FILENAME,
    STR_SLASH,
    STR_DOTCOSTUME,
    STR_CMD_FLY,
    STR_CMD_FLY_HELP,
    STR_CMD_TORCH,
    STR_CMD_TORCH_HELP,
    STR_CMD_DETACH,
    STR_CMD_DETACH_HELP,
    STR_CMD_COORDS,
    STR_CMD_COORDS_HELP,
    STR_CMD_LOADMAP,
    STR_CMD_LOADMAP_HELP,
    STR_CMD_LOADMAP_PROMPT,
    STR_CMD_MAPDEV,
    STR_CMD_MAPDEV_HELP,
    STR_CMD_NOCLIP,
    STR_CMD_NOCLIP_HELP,
    STR_CMD_MOV,
    STR_CMD_MOV_HELP,
    STR_CMD_TIME,
    STR_CMD_TIME_HELP,
    STR_CMD_PREVSPAWN,
    STR_CMD_PREVSPAWN_HELP,
    STR_CMD_NEXTSPAWN,
    STR_CMD_NEXTSPAWN_HELP,
    STR_CMD_RANDOMSPAWN,
    STR_CMD_RANDOMSPAWN_HELP,
    STR_CMD_SPAWNNPC,
    STR_CMD_SPAWNNPC_HELP,
    STR_CMD_MOVENPC,
    STR_CMD_MOVENPC_HELP,
    STR_CMD_DELETENPC,
    STR_CMD_DELETENPC_HELP,
    STR_CMD_CLEARNPC,
    STR_CMD_CLEARNPC_HELP,
    STR_CMD_LOADCOSTUME,
    STR_CMD_LOADCOSTUME_HELP,
    STR_CMD_BENPC,
    STR_CMD_BENPC_HELP,
    STR_CMD_RENAME,
    STR_CMD_RENAME_HELP,
    STR_CMD_ACCESSLEVEL,
    STR_CMD_ACCESSLEVEL_HELP,
    STR_END
};

unsigned long StringAddr(int id);
void WriteStrings();
unsigned long AddString(const char *str);
